### PR TITLE
Fix day of week function

### PR DESCRIPTION
**Pull request by twohue**
Re-ordered days of week in getDayNum() function in openair.js.

I found that due to my week starting on Sunday rather than Monday in OpenAir, that saving timesheets resulted in all of the time entered being moved back one day.

### CODE REVIEW

**Comment by crittermike** [comment]
Hmm, is this an option somewhere that I wasn't aware of? My timesheets all start on Monday. I just looked at "Personal Settings" and didn't see an option for this. Any ideas?

In any case, since it appears that it can go either way, I suppose the proper fix would be to detect which it is in your case and operate based on that. Thoughts?

**Comment by twohue** [comment]
I have gone through the code, and just barely figured out what's going on - Ignore this commit, I'm a dumb-ass.

I like your solution, though I'm not sure how to implement it just yet. Anything I can do to assist?

**Comment by crittermike** [comment]
I think in the function that you edited in your initial commit, it should just detect whether the first column says Sunday or Monday, and change the values in the array based on that.

**Comment by crittermike** [comment]
I can handle that whenever I get some time to work on OA Reborn again, but it might not be for a few weeks.

**Pull request closed without merging**
